MensPark/App_Admin/urls.py
from django.urls import path
from . import views

app_name = 'App_Admin'

urlpatterns = [
    path("", views.show_products, name="show_products"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('login/', views.admin_login, name="login"),
    path('logout/', views.admin_logout, name="logout"),
    path('add_products/', views.add_products, name='add_products'),
    path('all_products/', views.all_products, name="all_products"),
    path('edit_product/<int:product_id>', views.edit_product, name="edit_product"),
    path('delete_product/<int:product_id>', views.delete_product, name="delete_product"),
    path('all_outlets/', views.all_outlets, name='all_outlets'),
    path('add_outlets/', views.add_outlets, name='add_outlets'),
     path('edit_outlet/<int:outlet_id>', views.edit_outlet, name="edit_outlet"),
]

MensPark/MensPark/urls.py
from django import views
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Admin.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MensPark/App_Admin/models.py
from django.db import models

# Create your models here.
SIZE_CHOICES = [
    ('M', 'M'),
    ('L', 'L'),
    ('XL', 'XL'),
    ('M,L,XL', 'M,L,XL'),
]



class Category(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name
    

class Products(models.Model):
    name = models.CharField(max_length=200)
    gsm = models.CharField(max_length=50)
    price = models.IntegerField()
    image = models.ImageField(upload_to='product_images')
    size = models.CharField(max_length=50, choices=SIZE_CHOICES)
    made_in = models.CharField(max_length=50)
    description = models.CharField(max_length=1000, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=False, default='')
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
class Outlets(models.Model):
    name = models.CharField(max_length=200)
    cell = models.CharField(max_length=12)
    manager_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200) 
    map_link = models.CharField(max_length=200) 
    embed_link = models.CharField(max_length=1000, null=True)
    opening_hours = models.CharField(max_length=100) 
    closing_hours = models.CharField(max_length=100) 
    off_day = models.CharField(max_length=100)
    image = models.ImageField(upload_to='outlet_images')

    def __str__(self):
        return self.name

MensPark/App_Admin/forms.py
from dataclasses import fields
from django import forms

from .models import Outlets, Products


class ProductForm(forms.ModelForm):
    class Meta:
        model = Products
        fields = ['name', 'gsm', 'price', 'size',
                  'made_in', 'category', 'image', 'description']

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['placeholder'] = 'Enter Product Name'
        self.fields['gsm'].widget.attrs['placeholder'] = 'Enter GSM'
        self.fields['price'].widget.attrs['placeholder'] = 'Enter Price'
        self.fields['made_in'].widget.attrs['placeholder'] = 'Made In'
        self.fields['category'].widget.attrs['placeholder'] = 'Product Category'
        self.fields['description'].widget=forms.Textarea(attrs = {'class': 'form-control', 'placeholder': "Enter short description"})

class OutletForm(forms.ModelForm):
    class Meta:
        model = Outlets
        fields = '__all__'

MensPark/App_Admin/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .models import Outlets, Products

from .forms import OutletForm, ProductForm

# import googlemaps
# gmaps = googlemaps.Client(key='AlzaSyCn5pUJqC_L_7Br0rKKpLXxMgKvPKN-aGE')
# Create your views here.

def admin_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')      
        user = authenticate(username=username, password=password)
        
        if user is None:
            messages.success(request, 'User not found!', extra_tags='danger')
            return HttpResponseRedirect(reverse('App_Admin:login'))

        login(request, user)
        return HttpResponseRedirect(reverse('App_Admin:dashboard'))

    return render(request, 'App_Admin/login.html', context={})

@login_required
def admin_logout(request):
    logout(request)
    messages.success(request, 'Logged out successfully!', extra_tags='danger')
    return HttpResponseRedirect(reverse('App_Admin:login'))


@login_required
def dashboard(request):
    counts = Outlets.objects.count()
    all_outlets = Outlets.objects.all()
    return render(request, 'App_Admin/dashboard.html', context={'counts':counts, 'all_outlets':all_outlets})

@login_required
def add_products(request):
    form = ProductForm()

    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Product Added successfully!', extra_tags='success')
            return HttpResponseRedirect(reverse('App_Admin:add_products'))

    return render(request, 'App_Admin/add_products.html', context={'form':form})

@login_required
def all_products(request):
    products = Products.objects.all()
    return render(request, 'App_Admin/all_products.html', context={'items': products})

@login_required
def edit_product(request,product_id):
    product = Products.objects.get(id=product_id)
    form = ProductForm(instance=product)

    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Product Updated successfully!', extra_tags='success')
            return HttpResponseRedirect(reverse('App_Admin:all_products'))
    return render(request, 'App_Admin/edit_product.html', context={'form':form})

@login_required
def delete_product(request,product_id):
    product = Products.objects.get(id=product_id).delete()
    if product:
        messages.success(request, 'Product Deleted successfully!', extra_tags='success')
        return HttpResponseRedirect(reverse('App_Admin:all_products'))

def show_products(request):
    items = Products.objects.all()
    outlets = Outlets.objects.all()
    if request.method == "POST":
        key = request.POST.get('key')
        items = Products.objects.filter(name__contains=key)
        if items:
            messages.success(request, f'You\'ve Searched Product(s) {key}.', extra_tags='success')
        else:
            messages.success(request, 'The product is not available', extra_tags='danger')
            return HttpResponseRedirect(reverse('App_Admin:show_products'))

    map = 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2952.0594696309417!2d90.39785852559339!3d23.87422598409942!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3755c43bb8c21a3b%3A0xf37e844834c635fa!2sMascot%20Plaza%2C%20Uttara%2C%20Dhaka!5e0!3m2!1sen!2sbd!4v1649771713356!5m2!1sen!2sbd" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade">'
    return render(request, 'App_Admin/index.html', context={'items':items, 'latitude':23.815414889088338, 'longitude':90.36611284885306, 'map':map, 'outlets':outlets})


def all_outlets(request):
    outlets = Outlets.objects.all()
    return render(request, 'App_Admin/all_outlets.html', context={'outlets':outlets})

def add_outlets(request):
    form = OutletForm()

    if request.method == "POST":
        form = OutletForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Outlet Added successfully!', extra_tags='success')
            return HttpResponseRedirect(reverse('App_Admin:add_outlets'))

    return render(request, 'App_Admin/add_outlets.html', context={'form':form})

def edit_outlet(request,outlet_id):
    outlet = Outlets.objects.get(id=outlet_id)
    form = OutletForm(instance=outlet)

    if request.method == "POST":
        form = OutletForm(request.POST, request.FILES, instance=outlet)
        if form.is_valid():
            form.save()
            messages.success(request, 'Product Updated successfully!', extra_tags='success')
            return HttpResponseRedirect(reverse('App_Admin:all_outlets'))
    return render(request, 'App_Admin/edit_outlet.html', context={'form':form})

MensPark/templates/App_Admin/add_outlets.html
{% extends 'App_Admin/base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<main>
    <div class="container-fluid px-4 mt-3">
        {% if messages %}

        {% for message in messages %}
        <div class="alert alert-{{ message.extra_tags }} alert-dismissible fade show" role="alert">
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            {{message}}
        </div>
        {% endfor %}

        {% endif %}
        <div class="card mb-4 mt-3">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
                Add New Product
            </div>
            <div class="card-body">
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3">
                        {{ form.name|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.cell|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.manager_name|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.address|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.map_link|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.embed_link|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.opening_hours|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.closing_hours|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.off_day|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.image|as_crispy_field }}
                    </div>


                    <div class="d-grid gap-2">
                        <button type="submit" class="btn btn-primary" name="submit">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>

{% endblock %}

MensPark/templates/App_Admin/add_products.html
{% extends 'App_Admin/base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<main>
    <div class="container-fluid px-4 mt-3">
        {% if messages %}

        {% for message in messages %}
        <div class="alert alert-{{ message.extra_tags }} alert-dismissible fade show" role="alert">
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            {{message}}
        </div>
        {% endfor %}

        {% endif %}
        <div class="card mb-4 mt-3">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
                Add New Product
            </div>
            <div class="card-body">
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3">
                        {{ form.name|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.gsm|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.price|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.size|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.category|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.made_in|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.image|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.description|as_crispy_field }}
                    </div>


                    <div class="d-grid gap-2">
                        <button type="submit" class="btn btn-primary" name="submit">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>

{% endblock %}

MensPark/templates/App_Admin/all_outlets.html
{% extends 'App_Admin/base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<main>
    <div class="container-fluid px-4 mt-5">
        {% if messages %}

        {% for message in messages %}
        <div class="alert alert-{{ message.extra_tags }} alert-dismissible fade show" role="alert">
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            {{message}}
        </div>
        {% endfor %}

        {% endif %}
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
                All Products List
            </div>
            <div class="card-body">
                <table id="datatablesSimple">
                    <thead>
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Name</th>
                            <th scope="col">Image</th>
                            <th scope="col">Phone</th>
                            <th scope="col">Manager</th>
                            <th scope="col">Address</th>
                            <th scope="col">Opening Hr</th>
                            <th scope="col">Closing Hr</th>
                            <th scope="col">Off Day</th>
                            <th scope="col">Maps</th>
                            <th colspan="2" style="text-align: center;">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for outlet in outlets %}
                        <tr>
                            <td>{{outlet.id}}</td>
                            <td>{{outlet.name}}</td>
                            <td><img src="/media/{{outlet.image}}" width="60px" height="60px"></td>
                            <td>{{outlet.cell}}</td>
                            <td>{{outlet.manager_name}}</td>
                            <td>{{outlet.address}}</td>
                            <td>{{outlet.opening_hours}}</td>
                            <td>{{outlet.closing_hours}}</td>
                            <td>{{outlet.off_day}}</td>
                            <td><a href="{{outlet.map_link}}">Click</a></td>
                            <td><a href="{% url 'App_Admin:edit_outlet' outlet_id=outlet.id %}" class="btn btn-warning"><i class="fas fa-edit"></i></a></td>
                            <td><a href="" onclick="confirm('Want to delete product?')" class="btn btn-danger dlt"><i class="fas fa-trash"></i></button></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>

{% endblock %}

MensPark/templates/App_Admin/all_products.html
{% extends 'App_Admin/base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<main>
    <div class="container-fluid px-4 mt-5">
        {% if messages %}

        {% for message in messages %}
        <div class="alert alert-{{ message.extra_tags }} alert-dismissible fade show" role="alert">
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            {{message}}
        </div>
        {% endfor %}

        {% endif %}
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
                All Products List
            </div>
            <div class="card-body">
                <table id="datatablesSimple">
                    <thead>
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Name</th>
                            <th scope="col">Price</th>
                            <th scope="col">GSM</th>
                            <th scope="col">Size</th>
                            <th scope="col">Category</th>
                            <th scope="col">Details</th>
                            <th scope="col">Date</th>
                            <th colspan="2" style="text-align: center;">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in items %}
                        <tr>
                            <td>{{item.id}}</td>
                            <td>{{item.name}}</td>
                            <td>{{item.price}}</td>
                            <td>{{item.gsm}}</td>
                            <td>{{item.size}}</td>
                            <td>{{item.category}}</td>
                            <td>{{item.description}}</td>
                            <td>{{item.date|date:"M d, Y"}}</td>
                            <td><a href="{% url 'App_Admin:edit_product' product_id=item.id %}" class="btn btn-warning"><i class="fas fa-edit"></i></a></td>
                            <td><a href="{% url 'App_Admin:delete_product' product_id=item.id %}" onclick="confirm('Want to delete product?')" class="btn btn-danger dlt"><i class="fas fa-trash"></i></button></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>

{% endblock %}

MensPark/templates/App_Admin/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - SB Admin</title>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
    <link href="{% static 'admin/css/styles.css' %}" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js"
        crossorigin="anonymous"></script>
</head>

<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="{% url 'App_Admin:dashboard' %}">Men's Park Admin</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i
                class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown"
                    aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li>
                        <hr class="dropdown-divider" />
                    </li>
                    <li><a class="dropdown-item" href="{% url 'App_Admin:logout' %}" onclick="confirm('Want to logout?')">Logout</a></li>
                </ul>
            </li>
        </ul>
    </nav>

    {% include 'App_Admin/side_nav.html' %}

    <div id="layoutSidenav_content">
        <main>
            {% block body %}

            {% endblock %}
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid px-4">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; Your Website 2021</div>
                    <div>
                        <a href="#">Privacy Policy</a>
                        &middot;
                        <a href="#">Terms &amp; Conditions</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'admin/js/scripts.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="assets/demo/chart-area-demo.js"></script>
    <script src="assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
    <script src="{% static 'admin/js/datatables-simple-demo.js' %}"></script>
</body>

</html>

MensPark/templates/App_Admin/dashboard.html
{% extends 'App_Admin/base.html' %}
{% block body %}
<div class="container mt-5">
    <div class="row">
        <div class="col-xl-3 col-md-6">
            <div class="card bg-primary text-white mb-4">
                <div class="card-body"><b>{{counts}}</b> Total Outlets</div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>
            </div>
        </div>
    </div>
</div><br>
<div class="container mt-5">
    <h3>All Outlets</h3>
    <div class="row">
        {% for outlet in all_outlets %}
        <div class="col-xl-3 col-md-4">
            <div class="card bg-warning text-white mb-4">
                <div class="card-body"><b>{{outlet.name}}</b><br><b>{{outlet.cell}}</b></div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <a class="small text-white stretched-link" href="{{outlet.map_link}}">View Map</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

MensPark/templates/App_Admin/edit_outlet.html
{% extends 'App_Admin/base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<main>
    <div class="container-fluid px-4 mt-3">
        {% if messages %}

        {% for message in messages %}
        <div class="alert alert-{{ message.extra_tags }} alert-dismissible fade show" role="alert">
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            {{message}}
        </div>
        {% endfor %}

        {% endif %}
        <div class="card mb-4 mt-3">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
                Add New Product
            </div>
            <div class="card-body">
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3">
                        {{ form.name|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.cell|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.manager_name|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.address|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.map_link|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.embed_link|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.opening_hours|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.closing_hours|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.off_day|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.image|as_crispy_field }}
                    </div>


                    <div class="d-grid gap-2">
                        <button type="submit" class="btn btn-primary" name="submit">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>

{% endblock %}

MensPark/templates/App_Admin/edit_product.html
{% extends 'App_Admin/base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<main>
    <div class="container-fluid px-4 mt-3">
        {% if messages %}

        {% for message in messages %}
        <div class="alert alert-{{ message.extra_tags }} alert-dismissible fade show" role="alert">
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            {{message}}
        </div>
        {% endfor %}

        {% endif %}
        <div class="card mb-4 mt-3">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
                Add New Product
            </div>
            <div class="card-body">
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3">
                        {{ form.name|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.gsm|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.price|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.size|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.category|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.made_in|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.image|as_crispy_field }}
                    </div>
                    <div class="mb-3">
                        {{ form.description|as_crispy_field }}
                    </div>


                    <div class="d-grid gap-2">
                        <button type="submit" class="btn btn-primary" name="submit">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>

{% endblock %}

MensPark/templates/App_Admin/login.html
{% extends 'master.html' %}

{% block body %}
<div id="main-wrapper" class="container">
    <div class="row justify-content-center mt-3 mb-3">
        <div class="col-xl-10">
            <div class="card border-0">
                <div class="card-body p-0">
                    <div class="row no-gutters">
                        <div class="col-lg-6">
                            <div class="p-5">
                                <div class="mb-3">
                                    <h3 class="h4 font-weight-bold text-theme">Login</h3>
                                </div>
                                <!-- <h6 class="h5 mb-0">Just Do Register.</h6>
                    <p class="text-muted mt-2 mb-5">If You Really Want To Know, Look In The Register.</p> -->
                                {% if messages %}

                                {% for message in messages %}
                                <div class="alert alert-{{ message.extra_tags }} alert-dismissible fade show"
                                    role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                        <span class="sr-only">Close</span>
                                    </button>
                                    {{message}}
                                </div>
                                {% endfor %}

                                {% endif %}
                                <form method="POST" action="">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Username</label>
                                        <input type="text" class="form-control" name="username" />
                                    </div>
                                    <div class="form-group mb-5">
                                        <label for="exampleInputPassword1">Password</label>
                                        <input type="password" class="form-control" name="password" />
                                    </div>
                                    <button type="submit" class="btn btn-theme btn-block">Login</button>
                                </form>
                            </div>
                            <p class="text-muted text-center mb-2">New! need an account? <a href="user_register.php"
                                    class="text-primary ml-1">Register</a></p>
                        </div>
                        <div class="col-lg-6 d-none d-lg-inline-block">
                            <div class="account-block rounded-right">
                                <div class="overlay rounded-right"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end card-body -->
            </div>
            <!-- end card -->

            <!-- end row -->
        </div>
        <!-- end col -->
    </div>
    <!-- Row -->
</div>

{% endblock %}