MensPark/App_Admin/urls.py
from django.urls import path
from . import views

app_name = 'App_Admin'

urlpatterns = [
    path("", views.show_products, name="show_products"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('login/', views.admin_login, name="login"),
    path('logout/', views.admin_logout, name="logout"),
    path('add_products/', views.add_products, name='add_products'),
    path('all_products/', views.all_products, name="all_products"),
    path('edit_product/<int:product_id>', views.edit_product, name="edit_product"),
    path('delete_product/<int:product_id>', views.delete_product, name="delete_product"),
    path('all_outlets/', views.all_outlets, name='all_outlets'),
    path('add_outlets/', views.add_outlets, name='add_outlets'),
     path('edit_outlet/<int:outlet_id>', views.edit_outlet, name="edit_outlet"),
]

MensPark/MensPark/urls.py
from django import views
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Admin.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MensPark/templates/master.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'font/all.css' %}">
    <!--   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"> -->
    <!--   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script> -->

    <header>
        <div class="container" id="top">
            <div class="row">
                <div class="col-md-10 col-sm-12 col-xs-12">
                    <ul class=" list-group list-group-horizontal">
                        <li><i class='fas fa-envelope-open pr-2'></i><a href="#" class="pr-5"> Admin@mail.com</a></li>
                        <li><i class='fas fa-phone pr-2'></i><a href="#" class="pr-3"> +12 365 4789</a></li>
                    </ul>
                </div>
                <div class="col-md-2 col-sm-12 col-xs-12 text-left">
                    <i class='fab fa-facebook'></i>
                    <i class='fab fa-twitter-square'></i>
                    <i class='fab fa-google-plus-square'></i>
                </div>
            </div>
        </div>
        <nav class="navbar navbar-expand-md navbar-dark ownbg">
            <a class="navbar-brand text-white pl-5" href="index.php"><img src="./assets/images/logo.png" height="40px">
                PlantsWEB</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'App_Admin:show_products' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'App_Admin:login' %}">
                            Login
                        </a>
                    </li>
                </ul>
            </div>
        </nav>

        <!-- logout Modal-->

        <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="logoutModal"
            aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="logoutModal">Logout</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Are you sure to logout from the account?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Not now</button>
                        <button type="button" class="btn btn-danger"><a id="link" href="include/logout.php"
                                style="text-decoration: none;">Logout</a></button>
                    </div>
                </div>
            </div>
        </div>
    </header>
    {% block body %}

    {% endblock %}

    <!-------------First JQuery then Popper then Bootstrap then Fontawesome ------------->

    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="https://kit.fontawesome.com/417824116f.js" crossorigin="anonymous"></script>
    <script>
        $(document).ready(function () {
            $(".nav-tabs a").click(function () {
                $(this).tab('show');
            });
        });
    </script>